### ISSUE TITLE
Build isn't bundling dict files

### ISSUE THREAD

**Issue by mikesteele** [hexenq/kuroshiro-analyzer-kuromoji#5]
Hi! I'm trying to integrate Kuroshiro into this project (https://github.com/mikesteele/dual-captions) to allow users to have Kanji captions on YouTube & Netflix with Romaji captions underneath.

I have issues when I try to `Kuroshiro.init(new KuromojiAnalyzer())`. It's looking in my local filesystem for the dict files when (I think?) it should be bundling the files.

Here's the steps I took:

1. Cloned `kuroshiro` & `kuroshiro-analyzer-kuromoji`. I built both with `npm run build` and copied the `min.js` files to a folder. 

2. Created index.html 

```
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <script src="kuroshiro.min.js"></script>
  <script src="kuroshiro-analyzer-kuromoji.min.js"></script>
</head>
<body></body>
</html>
```

On trying to initialize Kuroshiro in the browser, I see:

<img width="1052" alt="screen shot 2018-08-13 at 12 36 46 pm" src="https://user-images.githubusercontent.com/3904909/44045255-f3a31d4a-9ef5-11e8-8655-7350b26cb7cd.png">

Why is it looking in the filesystem for these dict files when I browserified them?

**Comment by hexenq** [comment]
Hello @mikesteele . Do you browserify them like `file:///C:/demo/index.html` in browser? These file should be host on a live server like `http://localhost`. Or like what the error message said, under other supported schemas.

**Comment by hexenq** [comment]
You could also specify the path of the dicts using `dictPath` param.

**Comment by mikesteele** [comment]
Ok, I'l see if `dictPath` will work for my use case. Thanks!

**Comment by RobertB4** [comment]
I was having a similar issue today. I am using [Next.js](https://github.com/zeit/next.js/), which can serve static files only from a specific directory /static. the /dict directory of the Kuromoji analyzer is outside the /static directory by default (/node_modules/kuromoji/dict), which results in the following console error:
`GET http://localhost:3000/node_modules/kuromoji/dict/base.dat.gz 404 (Not Found)`
(the same error is repeated for every other file in the /dict directory)

I solved this issue by copying the /dict directory from /node_modules/kuromoji, pasting it inside the /static directory of my project and specifying the new `dictPath` like this.

```
const analyzer = new KuromojiAnalyzer({
        dictPath: '/static/dict/',
      });
```

 This way the browser can server the files correctly.

This doesn't feel like a good solution though. It would be nice to have this fixed so it works out of the box.
